# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patronprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronprofile',
            name='library_card_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
