# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('patronprofile', '0003_auto_20170619_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='borrowed',
            field=models.ManyToManyField(related_name='borrowed_by', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='patronprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
